### ISSUE TITLE
Compatibility with 5.3

### ISSUE THREAD

**Issue by ChickenNuggers** [facebook/luaffifb#5]
Is this program compatible with Lua 5.3, and if so, how can I get this working with Lua 5.3. If not, is there future planned support for Lua 5.3?

**Comment by ChickenNuggers** [comment]
And also, is there a way to compile without LuaRocks?

**Comment by daurnimator** [comment]
Have you tried? what errors have you gotten?

**Comment by daurnimator** [comment]
> the first problem is that luaffi uses lua_remove, which was moved from being a function to a macro in 5.3.

Here is a hacky fix:
```diff
diff --git a/ffi.h b/ffi.h
index ef00fa7..2bca60a 100644
--- a/ffi.h
+++ b/ffi.h
@@ -105,6 +105,10 @@ static char* luaL_prepbuffsize(luaL_Buffer* B, size_t sz) {
     }
     return luaL_prepbuffer(B);
 }
+#elif LUA_VERSION_NUM == 503
+static void (lua_remove)(lua_State *L, int idx) {
+    lua_remove(L, idx);
+}
 #endif
 
 /* architectures */
```

It now compiles:

```
In file included from call.c:44:0:
call_x64.h: In function ‘compile_extern_jump’:
call_x64.h:178:45: warning: unused parameter ‘jit’ [-Wunused-parameter]
 static void compile_extern_jump(struct jit* jit, lua_State* L, cfunction func, uint8_t* code)
                                             ^
call_x64.h:178:61: warning: unused parameter ‘L’ [-Wunused-parameter]
 static void compile_extern_jump(struct jit* jit, lua_State* L, cfunction func, uint8_t* code)
                                                             ^
In file included from call.c:44:0:
call_x64.h: In function ‘get_int’:
call_x64.h:352:51: warning: unused parameter ‘ct’ [-Wunused-parameter]
 static void get_int(Dst_DECL, const struct ctype* ct, struct reg_alloc* reg, int is_int64)
                                                   ^
call_x64.h: In function ‘add_int’:
call_x64.h:380:51: warning: unused parameter ‘ct’ [-Wunused-parameter]
 static void add_int(Dst_DECL, const struct ctype* ct, struct reg_alloc* reg, int is_int64)
                                                   ^
call_x64.h: In function ‘get_float’:
call_x64.h:414:53: warning: unused parameter ‘ct’ [-Wunused-parameter]
 static void get_float(Dst_DECL, const struct ctype* ct, struct reg_alloc* reg, int is_double)
                                                     ^
call_x64.h: In function ‘add_float’:
call_x64.h:452:53: warning: unused parameter ‘ct’ [-Wunused-parameter]
 static void add_float(Dst_DECL, const struct ctype* ct, struct reg_alloc* reg, int is_double)
                                                     ^
call.c: In function ‘get_extern’:
call.c:93:61: warning: unused parameter ‘type’ [-Wunused-parameter]
 int get_extern(struct jit* jit, uint8_t* addr, int idx, int type)
                                                             ^
call.c: In function ‘commit_code’:
call.c:219:48: warning: unused parameter ‘code’ [-Wunused-parameter]
 static void commit_code(struct jit* jit, void* code, size_t sz)
                                                ^
In file included from call.c:9:0:
call.c: At top level:
ffi.h:363:23: warning: ‘mk_complex_double’ defined but not used [-Wunused-function]
 static complex_double mk_complex_double(double real, double imag) {
                       ^
ffi.h:366:23: warning: ‘mk_complex_float’ defined but not used [-Wunused-function]
 static complex_double mk_complex_float(double real, double imag) {
                       ^
In file included from ctype.c:9:0:
ffi.h:109:14: warning: ‘lua_remove’ defined but not used [-Wunused-function]
 static void (lua_remove)(lua_State *L, int idx) {
              ^
In file included from ctype.c:9:0:
ffi.h:363:23: warning: ‘mk_complex_double’ defined but not used [-Wunused-function]
 static complex_double mk_complex_double(double real, double imag) {
                       ^
ffi.h:366:23: warning: ‘mk_complex_float’ defined but not used [-Wunused-function]
 static complex_double mk_complex_float(double real, double imag) {
                       ^
ffi.c: In function ‘get_cfunction_address’:
ffi.c:671:9: warning: unused variable ‘top’ [-Wunused-variable]
     int top = lua_gettop(L);
         ^
ffi.c: In function ‘callback_free’:
ffi.c:1446:16: warning: unused variable ‘p’ [-Wunused-variable]
     cfunction* p = (cfunction*) lua_touserdata(L, 1);
                ^
ffi.c: In function ‘ffi_string’:
ffi.c:2666:35: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             sz = nul ? nul - data : ct.array_size;
                                   ^
In file included from ffi.c:9:0:
ffi.c: At top level:
ffi.h:109:14: warning: ‘lua_remove’ defined but not used [-Wunused-function]
 static void (lua_remove)(lua_State *L, int idx) {
              ^
ffi.c:3153:13: warning: ‘push_builtin_undef’ defined but not used [-Wunused-function]
 static void push_builtin_undef(lua_State* L, struct ctype* ct, const char* name, int type)
             ^
parser.c: In function ‘check_token’:
parser.c:230:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (!next_token(L, P, &tok) || tok.type != type || (tok.type == TOK_TOKEN && (tok.size != strlen(str) || memcmp(tok.str, str, tok.size) != 0))) {
                                             ^
parser.c: In function ‘calculate_member_position’:
parser.c:416:56: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         int need_to_realign = bits_used + mt->bit_size > mt->base_size * CHAR_BIT;
                                                        ^
parser.c: In function ‘append_type_name’:
parser.c:1365:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < ct->pointers - ct->is_array; i++) {
                       ^
parser.c: In function ‘calculate_constant2’:
parser.c:2374:46: warning: signed and unsigned type in conditional expression [-Wsign-compare]
         return issize ? ctype_size(L, &type) : type.align_mask + 1;
                                              ^
In file included from parser.c:9:0:
parser.c: At top level:
ffi.h:109:14: warning: ‘lua_remove’ defined but not used [-Wunused-function]
 static void (lua_remove)(lua_State *L, int idx) {
              ^
In file included from parser.c:9:0:
ffi.h:363:23: warning: ‘mk_complex_double’ defined but not used [-Wunused-function]
 static complex_double mk_complex_double(double real, double imag) {
                       ^
ffi.h:366:23: warning: ‘mk_complex_float’ defined but not used [-Wunused-function]
 static complex_double mk_complex_float(double real, double imag) {
                       ^
gcc -O2 -fPIC -Wall -Wextra -I/usr/include -c call.c -o call.o -Idynasm
gcc -O2 -fPIC -Wall -Wextra -I/usr/include -c ctype.c -o ctype.o -Idynasm
gcc -O2 -fPIC -Wall -Wextra -I/usr/include -c ffi.c -o ffi.o -Idynasm
gcc -O2 -fPIC -Wall -Wextra -I/usr/include -c parser.c -o parser.o -Idynasm
gcc -shared -o ffi.so -L/usr/lib call.o ctype.o ffi.o parser.o
gcc -O2 -fPIC -Wall -Wextra -I/usr/include -c test.c -o test.o
gcc -shared -o ffi/libtest.so -L/usr/lib test.o
Missing dependency for http scm-0: cqueues >= 20150907
Missing dependency for lredis scm-0: cqueues >= 20150907
Updating manifest for /usr/lib/luarocks/rocks-5.3
luaffi scm-1 is now built and installed in /usr (license: BSD)

```

**Comment by colesbury** [comment]
I have some outstanding changes that add Lua 5.3 compatibility, and fix the unit tests. I haven't extensively tested it, but I'll push it to a 5.3 branch

**Comment by ChickenNuggers** [comment]
I'll be able to test it on Lua 5.3 for Debian and Arch. I believe I also have a few other VMs at home with Lua 5.3. I'll set up LuaRocks on those and see if I can get it running.

**Comment by alexbw** [comment]
Could you push changes to a 5.3 branch? I'm set up to test.

**Comment by colesbury** [comment]
Sure, I just pushed the lua53 branch:
https://github.com/facebook/luaffifb/tree/lua53

**Comment by ChickenNuggers** [comment]
@colesbury lua_remove isn't a function in Lua 5.3. 

Error:
```
 lua53 | /home/charles/builds/luaffifb  charles  desktop  20:36  2  luarocks make --local
gcc -O2 -fPIC -I/usr/include -c call.c -o call.o -Idynasm
call.c: In function ‘reserve_code’:
call.c:184:31: error: ‘lua_remove’ undeclared (first use in this function)
         ADDFUNC(jit->lua_dll, lua_remove);
                               ^
call.c:149:43: note: in definition of macro ‘ADDFUNC’
         func = func ? func : (cfunction) &NAME; \
                                           ^
call.c:184:31: note: each undeclared identifier is reported only once for each function it appears in
         ADDFUNC(jit->lua_dll, lua_remove);
                               ^
call.c:149:43: note: in definition of macro ‘ADDFUNC’
         func = func ? func : (cfunction) &NAME; \
```

Patch:
```diff
diff --git a/call.c b/call.c
index f8fb865..dcbb036 100644
--- a/call.c
+++ b/call.c
@@ -119,6 +119,12 @@ int get_extern(struct jit* jit, uint8_t* addr, int idx, int type)
     }
 }
 
+#if LUA_VERSION_NUM == 503
+static void (lua_remove)(lua_State *L, int idx) {
+    lua_remove(L, idx);
+}
+#endif
+
 static void* reserve_code(struct jit* jit, lua_State* L, size_t sz)
 {
     struct page* page;
```

**Comment by colesbury** [comment]
@ChickenNuggers, did you checkout the lua53 branch?

**Comment by ChickenNuggers** [comment]
Yes. I have. I pulled it and ran `git checkout lua53` about 10 minutes before bringing up that error message.

**Comment by alexbw** [comment]
Same error here.

**Comment by alexbw** [comment]
The patch doesn't help, seeing an error on calling a function `lua_xmove`

```
export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC -I/Users/awiltschko/anaconda/envs/_build_placehold_placehold_placehold_placehold_p/include -c call.c -o call.o -Idynasm
call.c:184:31: error: use of undeclared identifier 'lua_remove'; did you mean 'lua_xmove'?
        ADDFUNC(jit->lua_dll, lua_remove);
                              ^~~~~~~~~~
                              lua_xmove
call.c:149:43: note: expanded from macro 'ADDFUNC'
        func = func ? func : (cfunction) &NAME; \
                                          ^
/Users/awiltschko/anaconda/envs/_build_placehold_placehold_placehold_placehold_p/include/lua.h:166:16: note: 'lua_xmove' declared here
LUA_API void  (lua_xmove) (lua_State *from, lua_State *to, int n);
               ^
1 error generated.
```

**Comment by colesbury** [comment]
I haven't figured out what's different between our build configurations.
The lua53 branch builds with Lua 5.3.1 and passes the tests on my machine
and on the Travis-CI build: https://travis-ci.org/facebook/luaffifb

Maybe there's a difference in the way Lua is built? How have you installed
Lua 5.3?

**Comment by ChickenNuggers** [comment]
Incorrect. lua_xmove is recommended because lua_remove doesn't exist.

On Wed, Jan 6, 2016, 10:10 AM Sam Gross <notifications@github.com> wrote:

> I haven't figured out what's different between our build configurations.
> The lua53 branch builds with Lua 5.3.1 and passes the tests on my machine
> and on the Travis-CI build: https://travis-ci.org/facebook/luaffifb
>
> Maybe there's a difference in the way Lua is built? How have you installed
> Lua 5.3?
>
> On Wed, Jan 6, 2016 at 10:42 AM, Alex Wiltschko <notifications@github.com>
> wrote:
>
> > The patch doesn't help, seeing an error on calling a function lua_xmove
> >
> > export MACOSX_DEPLOYMENT_TARGET=10.8; gcc -O2 -fPIC
> -I/Users/awiltschko/anaconda/envs/_build_placehold_placehold_placehold_placehold_p/include
> -c call.c -o call.o -Idynasm
> > call.c:184:31: error: use of undeclared identifier 'lua_remove'; did you
> mean 'lua_xmove'?
> > ADDFUNC(jit->lua_dll, lua_remove);
> > ^~~~~~~~~~
> > lua_xmove
> > call.c:149:43: note: expanded from macro 'ADDFUNC'
> > func = func ? func : (cfunction) &NAME; \
> > ^
> >
> /Users/awiltschko/anaconda/envs/_build_placehold_placehold_placehold_placehold_p/include/lua.h:166:16:
> note: 'lua_xmove' declared here
> > LUA_API void (lua_xmove) (lua_State *from, lua_State *to, int n);
> > ^
> > 1 error generated.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/facebook/luaffifb/issues/5#issuecomment-169362478>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/luaffifb/issues/5#issuecomment-169372243>.
>
> Augusta Public Schools USD 402- Student Email

-- 

Charles Heywood <vandor2012@gmail.com>
Programmer :: Scripter :: Designer :: Administrator
https://github.com/ChickenNuggers

**Comment by alexbw** [comment]
I'm building against Lua 5.3.2, I can try 5.3.1 to see if that works.

**Comment by ChickenNuggers** [comment]
There should be no library changes; are you sure you applied the patch?

**Comment by ChickenNuggers** [comment]
I'll try compiling the 5.3.2 version on a c9.io Ubuntu environment.

**Comment by ChickenNuggers** [comment]
The current lua5.3 branch compiles in my environment; did someone apply the patch into ffi.h?

```
chickennuggers:~/workspace/luaffifb (lua53) $ git stash
Saved working directory and index state WIP on lua53: d806f1a Add support for Lua 5.3
HEAD is now at d806f1a Add support for Lua 5.3
chickennuggers:~/workspace/luaffifb (lua53) $ luarocks make --local
gcc -O2 -fPIC -I/usr/local/include -c call.c -o call.o -Idynasm
gcc -O2 -fPIC -I/usr/local/include -c ctype.c -o ctype.o -Idynasm
gcc -O2 -fPIC -I/usr/local/include -c ffi.c -o ffi.o -Idynasm
gcc -O2 -fPIC -I/usr/local/include -c parser.c -o parser.o -Idynasm
gcc -shared -o ffi.so -L/usr/local/lib call.o ctype.o ffi.o parser.o
gcc -O2 -fPIC -I/usr/local/include -c test.c -o test.o
gcc -shared -o ffi/libtest.so -L/usr/local/lib test.o
Updating manifest for /home/ubuntu/.luarocks/lib/luarocks/rocks
luaffi scm-1 is now built and installed in /home/ubuntu/.luarocks (license: BSD)

chickennuggers:~/workspace/luaffifb (lua53) $
```

**Comment by soumith** [comment]
@ChickenNuggers as we've been saying it was patched all along. Maybe there was a local cmake or luarocks cache that wasn't cleared in your case. Glad it worked out.

**Comment by ChickenNuggers** [comment]
@alexbw must have an old version as well then, seeing as they had the same issue. Closing by result of commit #d806f1ae30af77b2024d6c76868298db1b2980bc.

**Comment by alexbw** [comment]
Builds for me. 
FYI, issue I had is that `luarocks make` works, `luarocks install` does not.

**Comment by soumith** [comment]
@alexbw I think you aren't patching the luarocks in conda with our server patches: 
https://github.com/torch/luajit-rocks/commit/afee33c8f5779b0e88af5b48b1d144bc9aa41544
https://github.com/torch/luajit-rocks/commit/37fc2b970acb3d228fe2ddb2e5a6c51e331fe4cd
https://github.com/torch/luajit-rocks/commit/8afbe8310afe9bc5fe6ea4b035d11fd9d53afde6

**Comment by alexbw** [comment]
Looks like the patches just affect where packages are located. Does it
affect the internals at all?

**Comment by soumith** [comment]
It doesn't affect the internals, but the priority changes on two packages with the same name.
Our torch/rocks has a luaffi pointing to luaffifb, upstream moonrocks I think has a rockspec pointing to https://github.com/jmckaskill/luaffi which doesn't have all our latest changes.

**Comment by soumith** [comment]
oh, nevermind, luaffi on moonrocks also points to luaffifb. I didn't check properly. Ignore me.
